version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: esatto-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: esatto
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
