version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: esatto-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: esatto
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - esatto-network

  backend:
    build:
      context: ./esatto
    container_name: esatto-backend
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/esatto
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - CURRENCY_API_KEY=${CURRENCY_API_KEY}
    networks:
      - esatto-network

  frontend:
    build:
      context: ./esatto/frontend/esatto-front
    container_name: esatto-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - esatto-network

networks:
  esatto-network:
    driver: bridge

volumes:
  pgdata: